// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnttwzuqutvsfrhpnwrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudHR3enVxdXR2c2ZyaHBud3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzUxMzQsImV4cCI6MjA3MzYxMTEzNH0.HCU8B0bDJlz66G4lWPA5dhUXLkxbs9qa_L33b4GLkY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});